name: Run Tests

on: [push]

defaults:
  run:
    shell: bash

jobs:
  unit_tests:
    strategy:
      matrix:
        os: [ windows-latest, macos-11, macos-12, ubuntu-20.04, ubuntu-22.04 ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8  # v2
      - name: Set up Python 3.8
        uses: actions/setup-python@b55428b1882923874294fa556849718a1d7f2ca5  # v4.2.0
        with:
          python-version: 3.8
      - name: Install Pip Dependencies
        run: pip install nose coverage
      - name: Run Tests
        run: nosetests
      - name: Coveralls Parallel
        uses: coverallsapp/github-action@9ba913c152ae4be1327bfb9085dc806cedb44057  # 1.1.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          flag-name: run-${{ matrix.os }}
          parallel: true
  finish:
    needs: unit_tests
    runs-on: ubuntu-latest
    steps:
    - name: Coveralls Finished
      uses: coverallsapp/github-action@9ba913c152ae4be1327bfb9085dc806cedb44057  # 1.1.3
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        parallel-finished: true
